### ISSUE TITLE
提供.yml文件

### ISSUE THREAD

**Issue by TriYangZhang** [smiles724/InstructBio#1]
No such file or directory: '/root/code/InstructBio-master/MoleculeACE/Data/configures/default/SMILES.yml
您好，想复现您的代码，但缺失.yml文件，感谢。

**Comment by smiles724** [comment]
Hi, great thanks for your interest! 

As a matter of fact, our attention is mainly focusing on the study of semi-supervised learning. To reproduce the results of different machine learning methods on MoleculeACE, you can refer to the original benchmark codebase [https://github.com/molML/MoleculeACE/tree/main](url).

The .yml file can be accessed in this link: https://github.com/molML/MoleculeACE/tree/main/MoleculeACE/Data/configures/default

Best.

**Comment by TriYangZhang** [comment]
Thanks your answer!
可以解释一下下面图面里代码运行的问题吗。
![image](https://github.com/smiles724/InstructBio/assets/129965099/6e2e4254-5d12-4d14-b6ac-8eb1cb839e69)
感谢！
